[[main]]
  identifier = "The ML Handbook"
  name = "The ML Handbook"
  url = "handbook"
  weight = 1

[[main]]
  identifier = "How To"
  name = "How To"
  url = "information"
  weight = 2

[[main]]
  identifier = "Blog"
  name = "Blog Posts"
  url = "blog"
  weight = 3