[[main]]
  identifier = "docs"
  name = "The ML Handbook"
  url = "handbook"
  weight = 1

[[main]]
  identifier = "information"
  name = "Information"
  url = "information"
  weight = 2

[[main]]
  identifier = "blog"
  name = "Blog Posts"
  url = "blog"
  weight = 3